/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tdtt;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bvc
 */
public class NhanVien_Form extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien_Form
     */
    ConnectDB cndb=new ConnectDB();
    public Connection cn=cndb.getConnectDB();
    Statement stm;
    public NhanVien_Form() {
        try {
            initComponents();
            stm=cn.createStatement();
            load();
            truyendl();
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void executeQuery(String query){
        try{
            if(stm.executeUpdate(query)==1)
            {
                DefaultTableModel model =(DefaultTableModel)tbNhanVien.getModel();
                model.setRowCount(0);
                load();
            }
            else{
                JOptionPane.showMessageDialog(null, "false");
            }
        }
        catch(Exception ex){
                    ex.printStackTrace();
                    }
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        rdiNam = new javax.swing.JRadioButton();
        rdiNu = new javax.swing.JRadioButton();
        cbChucVu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        Them = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtNamVaoLam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSoCMND = new javax.swing.JTextField();
        txtNgayCap = new javax.swing.JTextField();
        txtNoiCap = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NHÂN VIÊN");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Tên Nhân Viên");

        jLabel4.setText("Địa Chỉ");

        jLabel5.setText("Ngày Sinh");

        jLabel6.setText("Giới Tính");

        jLabel7.setText("Chức Vụ");

        buttonGroup1.add(rdiNam);
        rdiNam.setText("Nam");
        rdiNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdiNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdiNu);
        rdiNu.setText("Nu");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pho Giam Doc", "Nhan Vien" }));
        cbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChucVuActionPerformed(evt);
            }
        });

        jLabel8.setText("Số Điện Thoại");

        Them.setText("Thêm");
        Them.setMaximumSize(new java.awt.Dimension(319, 265));
        Them.setPreferredSize(new java.awt.Dimension(319, 265));
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Địa Chỉ", "SDT", "Giới Tính", "Ngáy Sinh", "Chức Vụ", "Năm Vào Làm", "Số CMND", "Ngày cấp", "Nơi cấp", "Quốc tịch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        jLabel10.setText("Năm vào làm");

        jLabel9.setText("Số CMND");

        jLabel11.setText("Ngày cấp");

        jLabel12.setText("Nơi cấp");

        jLabel13.setText("Quốc tịch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNV)
                    .addComponent(txtDiaChi)
                    .addComponent(txtNgaySinh)
                    .addComponent(cbChucVu, 0, 197, Short.MAX_VALUE)
                    .addComponent(txtSDT)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rdiNam)
                        .addGap(30, 30, 30)
                        .addComponent(rdiNu))
                    .addComponent(txtNamVaoLam)
                    .addComponent(txtTenNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoCMND)
                            .addComponent(txtNoiCap)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtQuocTich))))
                .addGap(77, 77, 77))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdiNam)
                    .addComponent(rdiNu)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChucVuActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaNV.getText().equals("")||txtTenNV.getText().equals("")||txtDiaChi.getText().equals("")
            ||txtNgaySinh.getText().equals("")||txtSDT.getText().equals("")||txtNamVaoLam.getText().equals("")
            ||txtSoCMND.getText().equals("")||txtNgayCap.getText().equals("")||txtNoiCap.getText().equals("")
            ||txtQuocTich.getText().equals(""))
       {
           JOptionPane.showMessageDialog(rootPane, "Bạn vui lòng nhập hết thông tin mới");
           return;
       }
            String sqlSelect="select * from NhanVien where maNV='"+txtMaNV.getText()+"'";
                PreparedStatement pst=cn.prepareStatement(sqlSelect);           
                ResultSet rs=pst.executeQuery();
                 if(rs.next())
                 {
                     JOptionPane.showMessageDialog(rootPane, "Nhân viên này đã có trong hệ thống!");
                     
                 }
            
                 else{
                 String sex,a;
                     if(rdiNam.isSelected()){
                    sex="Nam";
                  }
                   else{
                   sex="Nu";
            }    
            
          
              String sql="insert into NhanVien values('"+txtMaNV.getText()+"','"+txtTenNV.getText()+"','"+txtDiaChi.getText()+"','"+txtSDT.getText()+"','"+sex+"','"+txtNgaySinh.getText()+"','"+cbChucVu.getSelectedItem()+"','"+txtNamVaoLam.getText()+"','"+txtSoCMND.getText()+"','"+txtNgayCap.getText()+"','"+txtNoiCap.getText()+"','"+txtQuocTich.getText()+"')";
          
            
          Statement stm= cn.createStatement();
          executeQuery(sql);
          int opt=JOptionPane.showConfirmDialog(rootPane, "Đã thêm nhân viên mới. Bạn có muốn cấp tài khoản cho nhân viên này?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);                                            
                     if(opt==JOptionPane.YES_OPTION)
                     {                    
//                         Main_Form mf = new Main_Form();
//                mf.setVisible(rootPaneCheckingEnabled);
                         TaiKhoan_Form tk=new TaiKhoan_Form();
                         tk.setVisible(rootPaneCheckingEnabled);
                         
                     }
                 }
      }catch(SQLException ex)
      {
          JOptionPane.showMessageDialog(this,"insert Tai Khoan Loi");
      }
    }//GEN-LAST:event_ThemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql1="Delete from TaiKhoan where maNV='"+txtMaNV.getText()+"'";
        String sql2="Delete from NhanVien where maNV='"+txtMaNV.getText()+"'";
        
        try{
            int result1 = stm.executeUpdate(sql1);
            int result2 = stm.executeUpdate(sql2);
            System.out.println("result1 :: "+ result1+"  result2 :: "+ result2);
            if(result1==0){
                JOptionPane.showMessageDialog(null, "Nhân viên này không có tài khoản để xóa");
            }
            
            if(result2!=0)
            {
                DefaultTableModel model =(DefaultTableModel)tbNhanVien.getModel();
                model.setRowCount(0);
                load();
            }
            else{
                JOptionPane.showMessageDialog(null, "Không có nhân viên để xóa");
            }
        }
        catch(Exception ex){
                    ex.printStackTrace();
           }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            if(txtMaNV.getText().equals("")||txtTenNV.getText().equals("")||txtDiaChi.getText().equals("")
            ||txtNgaySinh.getText().equals("")||txtSDT.getText().equals("")||txtNamVaoLam.getText().equals("")
            ||txtSoCMND.getText().equals("")||txtNgayCap.getText().equals("")||txtNoiCap.getText().equals("")
            ||txtQuocTich.getText().equals(""))
       {
           JOptionPane.showMessageDialog(rootPane, "Bạn vui lòng nhập hết thông tin mới");
           return;
       }
            {
                String sex,a;
                    if(rdiNam.isSelected()){
                    sex="Nam";
                }
                   else{
                   sex="Nu";
            }    
            
                String query="update NhanVien set ngaySinh='"+txtNgaySinh.getText()+"',  hoTen='"+txtTenNV.getText()+"',diaChi='"+txtDiaChi.getText()+"',sdt='"+txtSDT.getText()+"',gioiTinh='"+sex+"',chucVu='"+cbChucVu.getSelectedItem()+"',NamVaoLam='"+txtNamVaoLam.getText()+"',SoCMND='"+txtSoCMND.getText()+"',NgayCap='"+txtNgayCap.getText()+"',NoiCap='"+txtNoiCap.getText()+"',QuocTich='"+txtQuocTich.getText()+"' where maNV='"+txtMaNV.getText()+"'" ;
                executeQuery(query);
          
                }
      }catch(Exception ex)
      {
          JOptionPane.showMessageDialog(this,"isert Tai Khoan Loi");
      }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdiNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdiNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdiNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien_Form().setVisible(true);
            }
        });
    }
    public void truyendl(){
        tbNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tbNhanVien.getSelectedRow()>=0)
                {                
                txtMaNV.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),0)+"");
                txtTenNV.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),1)+"");
                txtDiaChi.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),2)+"");
                txtNgaySinh.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),5)+"");
                txtSDT.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),3)+"");
                if(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),4).equals("Nam")){
                    rdiNam.setSelected(rootPaneCheckingEnabled);
                }
                else{
                    rdiNu.setSelected(rootPaneCheckingEnabled);
                }
                cbChucVu.setSelectedItem(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),6)+"");
                txtNamVaoLam.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),7)+"");
                txtSoCMND.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),8)+"");
                txtNgayCap.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),9)+"");
                txtNoiCap.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),10)+"");
                txtQuocTich.setText(tbNhanVien.getValueAt(tbNhanVien.getSelectedRow(),11)+"");
                
                }
                
            }
        });
        
    }
    public ArrayList<NhanVien> TKList(){
        ArrayList<NhanVien> TKList = new ArrayList<>();
        try{
             String sql="select * from NhanVien";
        Statement stm=cn.createStatement();
        ResultSet rs=stm.executeQuery(sql);
        NhanVien tk;
        while(rs.next()){
            tk= new NhanVien(rs.getString("maNV"),rs.getString("hoTen"),rs.getString("diaChi"),rs.getString("gioiTinh"),rs.getString("ngaySinh"),rs.getString("chucVu"),rs.getString("NamVaoLam"),rs.getString("SoCMND"),rs.getString("NgayCap"),rs.getString("NoiCap"),rs.getString("QuocTich"),rs.getInt("sdt"));
            TKList.add(tk);
        }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,"Loi");
        }
       return TKList;
    }
    public void load(){
        ArrayList<NhanVien> list= TKList();
        DefaultTableModel model = (DefaultTableModel)tbNhanVien.getModel();
        Object[] row=new Object[12];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getMaNV();
            row[1]=list.get(i).getTenNV();
            row[2]=list.get(i).getDiaChi();
            row[3]=list.get(i).getSDT();
            row[4]=list.get(i).getNgaySinh();
            row[5]=list.get(i).getGioiTinh();
            row[6]=list.get(i).getChucVu();
            row[7]=list.get(i).getNamVaoLam();
            row[8]=list.get(i).getSoCMND();
            row[9]=list.get(i).getNgayCap();
            row[10]=list.get(i).getNoiCap();    
            row[11]=list.get(i).getQuocTich();
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Them;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdiNam;
    private javax.swing.JRadioButton rdiNu;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNamVaoLam;
    private javax.swing.JTextField txtNgayCap;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNoiCap;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
